columns_from_to_dict = {
    'Ano': 'Year',
    'Mês': 'Month',
    'UF': 'State',
    'IMPOSTO SOBRE IMPORTAÇÃO': 'Import Tax',
    'IMPOSTO SOBRE EXPORTAÇÃO': 'Export Tax',
    'IPI - FUMO': 'Excise Tax - Tobacco',
    'IPI - BEBIDAS': 'Excise Tax - Beverages',
    'IPI - AUTOMÓVEIS': 'Excise Tax - Automobiles',
    'IPI - VINCULADO À IMPORTACAO': 'Excise Tax - Linked to Import',
    'IPI - OUTROS': 'Excise Tax - Others',
    'IRPF': 'Individual Income Tax',
    'IRPJ - ENTIDADES FINANCEIRAS': 'Corporate Income Tax - Financial Entities',
    'IRPJ - DEMAIS EMPRESAS': 'Corporate Income Tax - Other Companies',
    'IRRF - RENDIMENTOS DO TRABALHO': 'Withholding Tax - Employment Income',
    'IRRF - RENDIMENTOS DO CAPITAL': 'Withholding Tax - Capital Income',
    'IRRF - REMESSAS P/ EXTERIOR': 'Withholding Tax - Transfers Abroad',
    'IRRF - OUTROS RENDIMENTOS': 'Withholding Tax - Other Income',
    'IMPOSTO S/ OPERAÇÕES FINANCEIRAS': 'Tax on Financial Transactions',
    'IMPOSTO TERRITORIAL RURAL': 'Rural Land Tax',
    'IMPOSTO PROVIS.S/ MOVIMENT. FINANC. - IPMF': 'Provisional Tax on Financial Transactions - IPMF',
    'CPMF': 'Provisional Contribution on Financial Transactions',
    'COFINS': 'Contribution for Social Security Financing',
    'COFINS - FINANCEIRAS': 'Contribution for Social Security Financing - Financial Entities',
    'COFINS - DEMAIS': 'Contribution for Social Security Financing - Others',
    'CONTRIBUIÇÃO PARA O PIS/PASEP': 'Contribution to PIS/PASEP',
    'CONTRIBUIÇÃO PARA O PIS/PASEP - FINANCEIRAS': 'Contribution to PIS/PASEP - Financial Entities',
    'CONTRIBUIÇÃO PARA O PIS/PASEP - DEMAIS': 'Contribution to PIS/PASEP - Others',
    'CSLL': 'Social Contribution on Net Profit',
    'CSLL - FINANCEIRAS': 'Social Contribution on Net Profit - Financial Entities',
    'CSLL - DEMAIS': 'Social Contribution on Net Profit - Others',
    'CIDE-COMBUSTÍVEIS (parc. não dedutível)': 'CIDE-Fuels (Non-Deductible Portion)',
    'CIDE-COMBUSTÍVEIS': 'CIDE-Fuels',
    'CONTRIBUIÇÃO PLANO SEG. SOC. SERVIDORES': 'Contribution to Social Security Plan for Public Servants',
    'CPSSS - Contrib. p/ o Plano de Segurid. Social Serv. Público': 'CPSSS - Contribution to Public Servants Social Security Plan',
    'CONTRIBUICÕES PARA FUNDAF': 'Contributions to FUNDAF',
    'REFIS': 'Tax Recovery Program (REFIS)',
    'PAES': 'Special Installment Program (PAES)',
    'RETENÇÃO NA FONTE - LEI 10.833, Art. 30': 'Withholding at Source - Law 10.833, Art. 30',
    'PAGAMENTO UNIFICADO': 'Unified Payment',
    'OUTRAS RECEITAS ADMINISTRADAS': 'Other Administered Revenues',
    'DEMAIS RECEITAS': 'Other Revenues',
    'RECEITA PREVIDENCIÁRIA': 'Social Security Revenue',
    'RECEITA PREVIDENCIÁRIA - PRÓPRIA': 'Social Security Revenue - Own Resources',
    'RECEITA PREVIDENCIÁRIA - DEMAIS': 'Social Security Revenue - Other Sources',
    'ADMINISTRADAS POR OUTROS ÓRGÃOS': 'Administered by Other Agencies'
}


states_list = ['AC', 'AL', 'AM', 'AP', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MG', 'MS', 'MT', 'PA', 'PB', 'PE', 'PI', 'PR', 'RJ', 'RN', 'RO', 'RR', 'RS', 'SC', 'SE', 'SP', 'TO']

english_months = {
    'Janeiro': 'January',
    'Fevereiro': 'February',
    'Março': 'March',
    'Abril': 'April',
    'Maio': 'May',
    'Junho': 'June',
    'Julho': 'July',
    'Agosto': 'August',
    'Setembro': 'September',
    'Outubro': 'October',
    'Novembro': 'November',
    'Dezembro': 'December'
}
